

server:
  port: 8082


spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://localhost:5432/${db_name}
    driver-class-name: org.postgresql.Driver
    username: ${username}
    password: ${password}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

# JWT config - must match your auth service
security:
  jwt:
    secret: "replace_with_the_same_base64_secret_used_by_auth_service"


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/