
server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/Snack
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: Solize@123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

# JWT config - must match your auth service
security:
  jwt:
    secret: "replace_with_the_same_base64_secret_used_by_auth_service"
