server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/Snack
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: Solize@123
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

# JWT config - must match your auth service
security:
  jwt:
    secret: "bW92aW5nbWFwc2Nob29sc2hvcnRncmF2aXR5YmVjb21pbmdicmVlemVmbGFtZWhlcnM="